<img style="float: left;;" src='Figures/alinco.png' /></a>
    
# <center> <font color= #000047> Actividad 2: Espacios Vectoriales ( Ejercicios )</font>
___



## Espacios vectoriales

Un [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial), $V$, sobre un <a href="https://es.wikipedia.org/wiki/Cuerpo_(matem%C3%A1ticas)">Campo</a>, $F$,  va a ser un [conjunto](http://relopezbriega.github.io/blog/2015/10/11/conjuntos-con-python/) en el que están definidas las operaciones de *<a href="https://es.wikipedia.org/wiki/Adici%C3%B3n_(matem%C3%A1ticas)">adición</a>* y  *multiplicación por <a href="http://es.wikipedia.org/wiki/Escalar_(matem%C3%A1tica)">escalares</a>*, tal que para cualquier par de elementos $x$ e $y$ en $V$, existe un elemento único $x + y$ en $V$, y para cada elemento $\alpha$ en $F$ y cada elemento $x$ en $V$, exista un único elemento $\alpha x$ en $V$, de manera que se cumplan las siguientes condiciones:

1. Para todo $x, y$ en $V$, $x + y = y + x$ ([conmutatividad](https://es.wikipedia.org/wiki/Conmutatividad) de la adición).

2. Para todo $x, y, z$ en $V$, $(x + y) + z = x + (y + z)$. (<a href="https://es.wikipedia.org/wiki/Asociatividad_(%C3%A1lgebra)">asociatividad</a> de la adición).

3. Existe un elemento en $V$ llamado $0$ tal que $x + 0 = x$ para todo $x$ en $V$.

4. Para cada elemento $x$ en $V$, existe un elemento $y$ en $V$ tal que $x + y = 0$.

5. Para cada elemento $x$ en $V$, $1 x = x$.

6. Para cada par, $\alpha, \beta$ en $F$ y cada elemento $x$ en $V$, $(\alpha \beta) x = \alpha (\beta x)$.

7. Para cada elemento $\alpha$ en $F$ y cada para de elementos $x, y$ en $V$, $\alpha(x + y) = \alpha x + \alpha y$.

8. Para cada par de elementos $\alpha, \beta$ en $F$ y cada elemento $x$ en $V$, $(\alpha +  \beta)x = \alpha x + \beta x$.

Los [espacios vectoriales](https://es.wikipedia.org/wiki/Espacio_vectorial) más comunes son $\mathbb{R}^2$, el cual representa el plano de 2 dimensiones y consiste de todos los pares ordenados de los [números reales](https://es.wikipedia.org/wiki/N%C3%BAmero_real):

$$\mathbb{R}^2 = \{(x, y): x, y \in \mathbb{R}\}$$

y $\mathbb{R}^3$, que representa el espacio ordinario de 3 dimensiones y consiste en todos los tríos ordenados de los  [números reales](https://es.wikipedia.org/wiki/N%C3%BAmero_real):

$$\mathbb{R}^3 = \{(x, y, z): x, y, z \in \mathbb{R}\}$$

Una de las grandes bellezas del [Álgebra lineal](http://relopezbriega.github.io/tag/algebra.html) es que podemos fácilmente pasar a trabajar sobre espacios de $n$ dimensiones, $\mathbb{R}^n$!

Tampoco tenemos porque quedarnos con solo los [números reales](https://es.wikipedia.org/wiki/N%C3%BAmero_real), ya que la definición que dimos de un [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) reside sobre un <a href="https://es.wikipedia.org/wiki/Cuerpo_(matem%C3%A1ticas)">Campo</a>; y los <a href="https://es.wikipedia.org/wiki/Cuerpo_(matem%C3%A1ticas)">campos</a> pueden estar representados por [números complejos](http://relopezbriega.github.io/blog/2015/10/12/numeros-complejos-con-python/). Por tanto también podemos tener [espacios vectoriales](https://es.wikipedia.org/wiki/Espacio_vectorial)  $\mathbb{C}^2, \mathbb{C}^3, \dots, \mathbb{C}^n$.

### Subespacios

Normalmente, en el estudio de cualquier estructura algebraica es interesante examinar subconjuntos que tengan la misma estructura que el [conjunto](http://relopezbriega.github.io/blog/2015/10/11/conjuntos-con-python/) que esta siendo considerado. Así, dentro de los [espacios vectoriales](https://es.wikipedia.org/wiki/Espacio_vectorial),  podemos tener [subespacios vectoriales](https://es.wikipedia.org/wiki/Subespacio_vectorial), los cuales son un subconjunto que cumplen con las mismas *propiedades* que el [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) que los contiene. De esta forma, $\mathbb{R}^3$ representa un [subespacio](https://es.wikipedia.org/wiki/Subespacio_vectorial) del [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) $\mathbb{R}^n$.



## Ejercicios:

<div class="alert alert-info"><strong>NOTA:</strong> 
Pueden adjuntar archivos word, jpg, pdf, etc.., para la solución de cada uno de los ejercicios</div>


**1.- Probar si el conjunto de matrices:**

$$\begin{Bmatrix} \begin{pmatrix}1 & \alpha\\ \beta & 1 \end{pmatrix} : \alpha, \beta \in \mathcal{R} \end{Bmatrix}$$

**es un espacio vectorial con su suma y producto usuales. Si no lo es, enunciar la serie de axiomas que no se satisfacen.**

In [10]:
# En el archivo adjunto "Solución a problemas" se comprueba uno a uno cada axioma o condición.
# Se concluye que el conjunto de matrices no es un espacio vectorial por lo siguiente:
# No es cerrado bajo suma.
# No es cerrado bajo multiplicación escalar.
# No existe un elemento neutro aditivo.
# No existe un inverso aditivo.

# para efectos de comprobación se usaran las siguientes matrices.  
import sympy as sy
A = sy.Matrix([[1,2],
             [3,1]])

B = sy.Matrix([[1,4],
             [5,1]])

C = sy.Matrix([[1,6],
             [7,1]])
x=2
y= 3

In [23]:
# No es cerrado bajo suma.
# Conmutatividad de la adición: x+y=y+x
# Aunque la condición se cumpla, la diagonal no son 1.
D=A+B
E=B+A
E




Matrix([
[2, 6],
[8, 2]])

In [33]:
# No es cerrado bajo multiplicación escalar: xA = Ax
# Aunque la condición se cumpla, la diagonal no son 1.
xA = x * A
Ax = A * x
xA

Matrix([
[2, 4],
[6, 2]])

In [20]:
# No existe un elemento neutro aditivo: A+0=A
mat_nul=A.nullspace()
mat_nul

[]

In [30]:
# No existe un inverso aditivo: A+(-A)=0
# Ya que la matriz nula no esta dentro del conjunto de matrices por tener diagonal o u no 1.
# Utilizaremos otra matriz dentro del conjunto para comprobar.
B_neg = (-1) * B
inv_ad = A + B_neg
inv_ad

Matrix([
[ 0, -2],
[-2,  0]])

**2.- Sea $V=\mathcal{R}^2$. Determinar si el conjunto:**

$$ H=\left\{(x,y): x^2+y^2 \leq 1 \right\}$$

**es un subespacio de V.**

In [ ]:
# En el archivo adjunto "Solución a problemas" se comprueba uno a uno cada axioma o condición.
# Se concluye que el conjunto H no es un subespacio de V por lo siguiente:
# No es cerrado bajo suma.
# No es cerrado bajo multiplicación escalar.

In [67]:
# No es cerrado bajo suma porque los resultados de la suma pueden ser mayores a 1.
import numpy as np
x = np.array([0.0, 0.5, 1.0, 1.5])
y = np.array([0.0, 0.5, 1.0, 1.5])
H = x**2 + y**2 <= 1
H

array([ True,  True, False, False])

In [71]:
# No es cerrado bajo multiplicación escalar porque los valores de la multiplicación puede ser mayores a 1.
import numpy as np
x = np.array([0.0, 0.5, 1.0, 1.5])
y = np.array([0.0, 0.5, 1.0, 1.5])
a = np.array([0.0, 0.5, 1.0, 1.5])
H = x**2 + y**2 
mult = a * H <= 1
mult

array([ True,  True, False, False])

**3.- Sea que $P_n$ defina el conjunto de todos los polinomios de grado menor que $n$, se definen las operaciones de suma y multiplicación por un escalar como:**

$$( p  + q )( x ) = p ( x ) + q ( x )$$
$$( \alpha p )( x ) = \alpha p ( x )$$

**para todos los números reales x . Verificar si $P_n$ es un espacio vectorial.**

In [151]:
#Vamos a comprobar directamente cada condición usando numpy.
# Para que el conjunto sea un espacio vectorial el grado de p y q debe ser menor que Pn 
# y ser verdadero para cada condicion o axioma.

# Con n = 3
# p = 1 + 2x + 3x^2
# q = 4 - 5x
import numpy as np
n = 3
p = np.array([1.0, 2.0, 3.0])   # n = 2
q = np.array([4.0, -5.0, 0.0])  # n = 1
p,q

(array([1., 2., 3.]), array([ 4., -5.,  0.]))

In [152]:
# 1. Comnutatividad.
# Si shape <= n la condición y el conjunto se cumplen porque p y q son de grado menor que Pn 
# y es cerrado bajo suma.
pq = p + q
p + q == q + p , pq.shape


(array([ True,  True,  True]), (3,))

In [153]:
# 2. Asociatividad.
# Si shape <= n la condición y el conjunto se cumplen porque p y q son de grado menor que Pn 
# y es cerrado bajo suma.
r = np.array([6.0, -7.0, -8.0])   # n = 3
qr = q + r
pqr = pq + r
pq + r == p + qr , pqr.shape

(array([ True,  True,  True]), (3,))

In [154]:
# 3. Neutro adititvo.
# La condición se cumple, p y q son de grado menor que Pn.
zr = np.zeros(3)
pq + zr == pq , pqr.shape

(array([ True,  True,  True]), (3,))

In [155]:
# 4. Inverso aditivo.
# La condición se cumple, p y q son de grado menor que Pn.
inv_pq = (-1) * pq
pq + inv_pq == 0, pqr.shape

(array([ True,  True,  True]), (3,))

In [156]:
# 5. Identidad.
1 * pq == pq,  pqr.shape

(array([ True,  True,  True]), (3,))

In [157]:
# 6. Cierre bajo multiplicación escalar.
a = 3
ap = a * p
mult_pq = p * q
apq = a * p * q
a * mult_pq == ap * q ,  apq.shape

(array([ True,  True,  True]), (3,))

In [158]:
# 7. Distributiva por un escalar
aq= a * q
sum_apq = ap + aq
a * (p + q) == ap + aq , sum_apq.shape

(array([ True,  True,  True]), (3,))

In [159]:
# 8. Distributiva por un vector
b = 6
bp= b * p
sum_abp= ap + bp
(a + b) * p == ap + bp , sum_abp.shape

(array([ True,  True,  True]), (3,))

In [115]:
# Conclusión.
# Para todas las condiciones se cumple cuando p y q son de grado menor que Pn
# Por lo tanto Pn es un espacio vectorial.

**4.- Considere el conjunto $M_{2x2}$ de las matrices de $(2x2)$ y las operaciones convencionales de suma de matrices y producto de una matriz por un escalar. Verificar que este conjunto cumple con los 10 axiomas para ser un espacio vectorial.**

In [160]:
# Vamos a comprobar directamente cada condición usando sympy.
# Para que el conjunto sea un espacio vectorial debe mantener su tamaño M(2x2) 
# y ser verdadero para cada condicion o axioma.

# Elegimos 3 matrices de (2 x 2) y dos escalares.
import sympy as sp
a,b,c,d,e,f,g,h,o,p,q,r, alfa, beta = sp.symbols(
    'a b c d e f g h o p q r alfa beta', real=True)
A = sy.Matrix(((a,b),
               (c,d,)))

B = sy.Matrix(((e,f),
               (g,h)))

C = sy.Matrix(((o,p),
               (q,r)))



In [162]:
# 1. Comnutatividad.
sum_ab= A + B
A + B == B + A , sum_ab.shape , sum_ab

(True,
 (2, 2),
 Matrix([
 [a + e, b + f],
 [c + g, d + h]]))

In [163]:
# 2. Asociatividad.
sum_abc = (A + B) + C
(A + B) + C == A + (B + C), sum_abc.shape , sum_abc

(True,
 (2, 2),
 Matrix([
 [a + e + o, b + f + p],
 [c + g + q, d + h + r]]))

In [164]:
# 3. Neutro adititvo.
Z = sp.zeros(2, 2) # Matriz nula de 2x2.
sum_az = A + Z
A + Z == A, sum_az.shape , sum_az

(True,
 (2, 2),
 Matrix([
 [a, b],
 [c, d]]))

In [165]:
# 4. Inverso aditivo.
neg_a = (-1) * A
invad_a = A + neg_a
A + neg_a == sp.zeros(2, 2), invad_a.shape , invad_a   

(True,
 (2, 2),
 Matrix([
 [0, 0],
 [0, 0]]))

In [166]:
# 5. Identidad.
id_a= 1 * A
1 * A == A, id_a.shape, id_a

(True,
 (2, 2),
 Matrix([
 [a, b],
 [c, d]]))

In [173]:
# 6. Cierre bajo multiplicación escalar.
abA= alfa * beta * A
(alfa * beta) * A == alfa * (beta * A), abA.shape, abA


(True,
 (2, 2),
 Matrix([
 [a*alfa*beta, alfa*b*beta],
 [alfa*beta*c, alfa*beta*d]]))

In [178]:
# 7. Distributiva por un escalar
aAB= (alfa * A) + ( alfa * B)
left  = alfa*(A + B)
right = alfa*A + alfa*B
left.equals(right), aAB.shape , aAB

(True,
 (2, 2),
 Matrix([
 [a*alfa + alfa*e, alfa*b + alfa*f],
 [alfa*c + alfa*g, alfa*d + alfa*h]]))

In [179]:
# 8. Distributiva por un vector
abA= alfa*A + beta*A
left  = (alfa + beta) * A
right = alfa*A + beta*A
left.equals(right), abA.shape , abA

(True,
 (2, 2),
 Matrix([
 [a*alfa + a*beta, alfa*b + b*beta],
 [alfa*c + beta*c, alfa*d + beta*d]]))

In [ ]:
#Conclusión
# Todas las condiciones de cumplen conservando matrices de 2x2
# por lo tanto el conjunto M2x2 es un espacio vectorial.